### ISSUE TITLE
Build issue with GCC 11

### ISSUE THREAD

**Issue by tuliom** [sphde/sphde#53] opened 2020-07-06 18:18 UTC
GCC 11 is detecting a new error in SPHDE:

```
src/sassim.cpp:523:35: error: 'this' pointer null [-Werror=nonnull]
  523 |   anchor->uncommitted->insertNode (nn, keys, (unsigned long) anchorBlock);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/sasanchr.h:18,
                 from src/sassim.cpp:40:
src/ultree.h:42:18: note: in a call to non-static member function 'uLongTreeNode* uLongTreeNode::insertNode(uLongTreeNode**, search_t, info_t)'
   42 |   uLongTreeNode *insertNode ( uLongTreeNode **root,
      |                  ^~~~~~~~~~
```

**Comment by munroesj52** [comment] 2020-07-06 20:13
This code is working as designed. Compiles clean with gcc10

>   anchor->uncommitted = NULL;
>   anchor->free = NULL;
>   anchor->used = NULL;
>   anchor->region = NULL;
>   anchor->allocated = NULL;
>   nn = &(anchor->uncommitted);
> 
>   keys = nodeToLong (0, SizeToLog2 (SegmentSize));
>   anchor->uncommitted->insertNode (nn, keys, (unsigned long) anchorBlock);

This is init code and yes anchor->uncommitted = NULL; on the first call. but the code checks for this and 

>     uLongTreeNode *n = (uLongTreeNode *)SASNearAlloc(root, sizeof(uLongTreeNode));
>     n->init(k, i);
> 
>     p = *root;
>     if (*root != NULL)
> 	{ ...
> 	} else {
> 	    *root = n;
> 	};

this seems a little too pedantic. Need to bring Bill into this

**Comment by munroesj52** [comment] 2020-07-07 15:03
The problem is that ultree and uLongTreeNode are common code used for all power-of-two-buddy lists. Most of these lists can be empty at anytime (root-> NULL). This is old code (1995) back when C++ was the solution to all problems.

This is weird for C++ given that all the function members are inline or static. But C++ needs the pointer to match on the type at compile time. And now the compiler is getting more pedantic about pointers. Not sure why this is betting enforced now?

The long term solution is to rewrite ultree to straight C. But for now it is best to use "-Wno-nonnull’ ?  Hopefully that will not cause problems for older compilers.

**Comment by tuliom** [comment] 2020-07-07 22:15
>  But for now it is best to use "-Wno-nonnull’ ? Hopefully that will not cause problems for older compilers.

Yep.  It has been available at least since GCC 4.8:
https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Warning-Options.html#Warning-Options

**Comment by segher** [comment] 2020-07-20 15:58
It is not pedantic; your code is simply not valid C++ if you do this.

Also, it is just a warning.  Don't use `-Werror`, or use `-Wno-nonnull`, or use
`-Wno-error=nonnull`?  It is much better to just fix the code, of course, if you can.

**Comment by munroesj52** [comment] 2020-07-20 21:19
As I explained above the functions of ultree would have to be rewritten in C to totally eliminate this warning.. The the problem is the ultree can be empty (root pointer null) at any time, so the implementation checks for and handles this internally. 
So this warning adds no value to code that has been working since the late 1990s. My mistake was to use C++ at all, but it was all the rage at time.
It just happens to flag an example in the SASinit code where I initialize the root pointer to NULL (empty) for a specific ultree in scope before I populate the tree. Otherwise it would never know.

**Comment by munroesj52** [comment] 2020-07-22 16:03
Take a look at https://github.com/sphde/sphde/pull/54

**Comment by rzinsly** [comment] 2020-07-24 13:37
Fixed by @munroesj52: https://github.com/sphde/sphde/commit/10897accedb5adc6ca54c91e49e482bb853cb59d

**Closed by rzinsly** 2020-07-24 13:37 UTC
